### PR TITLE
32 bit client support

### PR DESCRIPTION
**Pull request by henca**
Adding switch -3 to allow limiting fileid and cookie to 32 bits for compability with some old 32-bit applications on clients.

### CODE REVIEW

**Comment by henca** [comment]
This is a pull request for issue #44 at https://github.com/unfs3/unfs3/issues/44

**Comment by CendioOssman** [comment]
Thank you! This looks like a good change. Just let me have a closer look and we can then merge it.

**Review by CendioOssman — CHANGES_REQUESTED** [review]
Sorry for the delay. Changes look good to me.

Commits are a bit funky, though. Not sure what happened there. Could you make sure there is one commit that turns this in to a flag, and one commit for changing the cookie behaviour.

**Comment by henca** [comment]
The commits got a bit messed up when I tried to sign my commit with a gpg key. That attempt to sign caused an extra commit. This ended up in two identical commits, one signed and one unsigned. Finally it caused a third commit which only was a merge of those two identical commits, of course without any conflict.

**Comment by henca** [comment]
Do you want me to redo the commits and create a new pull request?

**Comment by CendioOssman** [comment]
New commits, please. But not a new PR. You can force push things to this branch and it should update properly.

**Comment by henca** [comment]
Ok, I made a local removal of the branch and remade the changes on a new branch with the same name which I then force-pushed to the remote repo. Even though I had the -S flag to git commit I didn't get any signoff in the commit, but maybe that is not so important. 

Before creating the new branch I made a pull from upstream... Somehow that pull now seems to be a part of this pull request which was not my intention, I only wanted to be in sync with the latest greatest.

**Comment by CendioOssman** [comment]
You don't need to sync things if you don't want to. We can usually handle that as we merge. :)

That said, doing a merge is not the ideal way to do it. What you should do is a `git rebase`. Generally `git rebase -i master` will give you what you want.

So please give it another go so we can avoid that merge commit.

Also, a reminder to split out the changed cookie behaviour to its own commit. It's easily overlooked for those browsing the history otherwise.

**Comment by henca** [comment]
I was able to revert with "git rebase --onto 9ed6a635fafc43fd97d8977a9ea4f075dde8c96e 32_bit_client_support". Now it is separated into two different commits. The first commit only truncates fileid, even though the help text says that both fileid and cookie is truncated. The second commit really also truncates the cookie and adds the changes to the man-page.

**Pull request merged**
